"""hashed password

Revision ID: 211163b6327c
Revises: caf715f0e1e7
Create Date: 2024-09-03 15:53:50.500499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211163b6327c'
down_revision = 'caf715f0e1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
